# Generated by Django 3.2.5 on 2021-07-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.myuser')),
                ('registration_code', models.CharField(max_length=50)),
                ('is_admin_account', models.BooleanField(default=True)),
            ],
        ),
    ]
