# Generated by Django 3.2.5 on 2021-07-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.myuser')),
                ('phone_no', models.IntegerField(max_length=15)),
                ('website', models.URLField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('is_client_account', models.BooleanField(default=True)),
            ],
        ),
    ]
